trigger:
- master

pool:
  name: default

steps:
- task: Maven@3
  displayName: Rashmika-Manawadu
  inputs:
    mavenPomFile: 'java-tomcat-sample/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    #goals: 'deploy'
