trigger:
- master

pool:
  name: default

steps:
- task: Maven@3
  displayName: Rashmika-Manawadu
  inputs:
    mavenPomFile: 'java-tomcat-sample/pom.xml'
    publishJUnitResults: false
    mavenVersionOption: 'Default'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    #goals: 'deploy'
