trigger:
- master

pool:
  name: default

steps:
- task: Maven@3
  displayName: Rashmika-Manawadu
  inputs:
    mavenPomFile: 'java-tomcat-sample/pom.xml'
    publishJUnitResults: false
    mavenVersionOption: 'Default'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    goals: 'package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/java-tomcat-sample/target'
    ArtifactName: 'rashmika-manawadu'
    includeRootFolder: false
    Contents: '**/*.war'
